language: csharp
dist: trusty
mono: none
dotnet: 2.0.0

install:
- dotnet restore

script:
# Only run codecov:
# - he build
# - he test
# - he report
# but most importantly
# - he protec
- sh codecov.sh
